export const GET_PRODUCTS_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCT_FAIL'

export const GET_PRODUCT_DETAIL_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_DETAIL_FAIL = 'GET_PRODUCT_FAIL'
export const GET_PRODUCT_DETAIL_RESET = 'GET_PRODUCT_DETAIL_RESET'
